import User from "../../../types/user";

const users: User[] = [
    { name: "Bad", lastname: "Bunny", maxScore: 395 },
    { name: "John", lastname: "Smith", maxScore: 723 },
    { name: "Emily", lastname: "Johnson", maxScore: 599 },
    { name: "Olivia", lastname: "Brown", maxScore: 855 },
    { name: "James", lastname: "Davis", maxScore: 350 },
    { name: "Liam", lastname: "Miller", maxScore: 800 },
    { name: "Isabella", lastname: "Wilson", maxScore: 670 },
    { name: "William", lastname: "Moore", maxScore: 910 },
    { name: "Sophia", lastname: "Taylor", maxScore: 561 },
    { name: "Oliver", lastname: "Anderson", maxScore: 830 },
    { name: "Mason", lastname: "Thomas", maxScore: 300 },
    { name: "Charlotte", lastname: "Jackson", maxScore: 410 },
    { name: "Amelia", lastname: "White", maxScore: 789 },
    { name: "Michaela", lastname: "Harris", maxScore: 520 },
    { name: "Noah", lastname: "Martin", maxScore: 645 },
    { name: "Lucas", lastname: "Clark", maxScore: 735 },
    { name: "Ethan", lastname: "Lewis", maxScore: 800 },
    { name: "Grace", lastname: "Walker", maxScore: 570 },
    { name: "Chloe", lastname: "Roberts", maxScore: 467 },
    { name: "Benjamin", lastname: "Young", maxScore: 669 },
    { name: "Jack", lastname: "King", maxScore: 820 },
    { name: "Zoe", lastname: "Scott", maxScore: 910 },
    { name: "Henry", lastname: "Adams", maxScore: 552 },
    { name: "Mia", lastname: "Baker", maxScore: 638 },
    { name: "Ella", lastname: "Gonzalez", maxScore: 747 },
    { name: "Daniel", lastname: "Nelson", maxScore: 852 },
    { name: "Alexander", lastname: "Carter", maxScore: 592 },
    { name: "Jack", lastname: "Mitchell", maxScore: 700 },
    { name: "Aiden", lastname: "Perez", maxScore: 650 },
    { name: "Samuel", lastname: "Robinson", maxScore: 772 },
    { name: "Victoria", lastname: "Young", maxScore: 403 },
    { name: "Madison", lastname: "Evans", maxScore: 880 },
    { name: "Sebastian", lastname: "Hernandez", maxScore: 456 },
    { name: "Megan", lastname: "Campbell", maxScore: 950 },
    { name: "Logan", lastname: "Gonzalez", maxScore: 540 },
    { name: "Matthew", lastname: "Simmons", maxScore: 783 },
    { name: "Harper", lastname: "Bryant", maxScore: 604 },
    { name: "Jack", lastname: "Alexander", maxScore: 760 },
    { name: "Samuel", lastname: "Russell", maxScore: 585 },
    { name: "Scarlett", lastname: "Gray", maxScore: 700 },
    { name: "Gabriel", lastname: "James", maxScore: 788 },
    { name: "Lily", lastname: "Watson", maxScore: 670 },
    { name: "Nathan", lastname: "Brooks", maxScore: 580 },
    { name: "Samuel", lastname: "Chavez", maxScore: 855 },
    { name: "Oliver", lastname: "Stewart", maxScore: 810 },
    { name: "Lucas", lastname: "Young", maxScore: 903 },
    { name: "Sophia", lastname: "Miller", maxScore: 600 },
    { name: "Charlotte", lastname: "Johnson", maxScore: 740 },
    { name: "William", lastname: "Taylor", maxScore: 675 },
    { name: "Amelia", lastname: "Roberts", maxScore: 491 }
];

export default users;